version: "3"
services:
  tle-fetcher:
    image: qaware/tle-fetcher:1.0.0
    depends_on:
      - promtail
    ports:
      - "8080:8080"
    volumes:
      - tle_fetcher_logs:/logs
    networks:
      - default

  sky-map:
    image: qaware/sky-map:1.0.0
    environment:
      - QUARKUS_REST_CLIENT_TLE_FETCHER_URL=http://tle-fetcher:8080
    depends_on:
      - tle-fetcher
      - promtail
    ports:
      - "8088:8088"
    volumes:
      - sky_map_logs:/logs
    networks:
      - default

  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards/
    networks:
      - default

  loki:
    image: grafana/loki:2.7.3
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    volumes:
      - loki_data:/loki
    networks:
      - default

  promtail:
    image: grafana/promtail:2.7.3
    depends_on:
      - loki
    command:
      - '-config.file=/etc/promtail/promtail.yaml'
    volumes:
      - ./promtail:/etc/promtail
      - tle_fetcher_logs:/tle-fetcher-logs
      - sky_map_logs:/sky-map-logs
    networks:
      - default

volumes:
  tle_fetcher_logs: {}
  sky_map_logs: {}
  grafana_data: {}
  loki_data: {}

networks:
  default:
    driver: bridge
