version: "3"
services:
  tle-fetcher:
    image: qaware/tle-fetcher:1.0.0
    ports:
      - "8080:8080"
    volumes:
      - tle_fetcher_logs:/logs
    networks:
      - default

volumes:
  tle_fetcher_logs: {}

networks:
  default:
    driver: bridge
